kind: Namespace
apiVersion: v1
metadata:
  name: ed-gen-nginx
  labels:
    name: ed-gen-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ed-gen-nginx
  namespace: ed-gen-nginx
  labels:
    app: ed-gen-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ed-gen-nginx
  template:
    metadata:
      labels:
        app: ed-gen-nginx
    spec:
      containers:
      - name: ed-gen-nginx
        image: chadtsigler/ed-gen-nginx:latest


